# Changes here will be overwritten by Copier
_commit: v0.0.13
_src_path: gh:AmpelAstro/copier-ampel
plugin_description: Apache Kafka support for the Ampel system.
plugin_name: kafka
plugin_org: AmpelAstro
plugin_version: 0.10.0a0
user_email: jakob.van.santen@desy.de
user_name: Jakob van Santen
version_cap: <0.11
